region: eu-west-3

function_name: search-flat
handler: service.handler
description: reads last mails on a gmail inbox containing adds for flat rental
runtime: python3.10
role: lambda_basic_execution 

# S3 upload requires appropriate role with s3:PutObject permission
# (ex. basic_s3_upload), a destination bucket, and the key prefix
bucket_name: 'search-flat'
s3_key_prefix: 'lambdas/answer-emails/'

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
aws_access_key_id: AKIAYYI727HXCGINBE6P
aws_secret_access_key: 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

# dist_directory: dist
# timeout: 15
# memory_size: 512
# concurrency: 500
#

# Experimental Environment variables
environment_variables:
    FROM_EMAIL: victor.recherche.appartement@gmail.com
    NAME: victor.coatalem
    PHONE: 0760912574

# If `tags` is uncommented then tags will be set at creation or update
# time.  During an update all other tags will be removed except the tags
# listed here.
#tags:
#    tag_1: foo
#    tag_2: bar

# Build options
build:
  source_directories: lib # a comma delimited list of directories in your project root that contains source to package.
